Transform: AWS::Serverless-2016-10-31
Description: Hemp Conduit User Handler
Resources:
  handler:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: go1.x
      Handler: handler
      CodeUri: .
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables: